gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper2_grouper_data
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper2_grouper_ui
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper2_grouper_ws
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper2_idp
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper2_midpoint_server
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper2_mq
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper2_sources
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper2_targets
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_directory
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_grouper_daemon
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_grouper_data
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_grouper_data_2
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_grouper_ui
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_idp
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_midpoint_server
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_sources
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_targets
gcloud container images delete --quiet gcr.io/$PROJECT_ID/confluence-server-mysql
gcloud container images delete --quiet gcr.io/$PROJECT_ID/directory
gcloud container images delete --quiet gcr.io/$PROJECT_ID/grouper_daemon
gcloud container images delete --quiet gcr.io/$PROJECT_ID/idp
gcloud container images delete --quiet gcr.io/$PROJECT_ID/mq
gcloud container images delete --quiet gcr.io/$PROJECT_ID/rabbitmq
gcloud container images delete --quiet gcr.io/$PROJECT_ID/sources
gcloud container images delete --quiet gcr.io/$PROJECT_ID/tier
